@host = http://127.0.0.1:4000

### Register endpoint
POST {{host}}/users/register
Content-Type: application/json

{
   "email": "q@q.co",
   "password": "Q@q.co12"
}

### Login endpoint
POST {{host}}/users/login
Content-Type: application/json

{
   "email": "q@q.co",
   "password": "Q@q.co12"
}

### Me endpoint
GET {{host}}/users/me

### Logout endpoint
GET {{host}}/users/logout

### Hi endpoint
GET {{host}}/hi
